---
- name: Install common dnsmasq settings for this host
  template: src=vastra.conf.j2 dest=/etc/dnsmasq.d/vastra.conf
  
- name: Become our subnet's DNS server
  template: src=dns.conf.j2 dest=/etc/dnsmasq.d/dns.conf
- template: src=dhclient.conf.j2 dest=/etc/dhcp/dhclient.conf

- name: Become a DHCP server
  template: src=dhcp.conf.j2 dest=/etc/dnsmasq.d/dhcp.conf

- name: Become a PXEboot server.
  copy: src=pxeboot.conf dest=/etc/dnsmasq.d/

# We could also write some static mappings here into /etc/hosts
# but let's try to avoid that if we can

# See also the vpn role, which installs scripts openvpn-up.sh (and -down.sh)
# that create (and delete) a file in /etc/dnsmasq.d/ called alseageo.conf

# Hopefully this will stop dhclient from stomping all over resolv.conf
- name: Reload networking service
  service: name=networking state=reloaded

- name: Install a good resolv.conf file pointing at us.
  template: src=resolv.conf.j2 dest=/etc/resolv.conf
