---
# setup.yml -- set up a server completely

- hosts: svxlink
  remote_user: link
  become: yes
  become_user: root
  roles:
  - svxlink

- hosts: web
  remote_user: link
  become: yes
  become_user: root
  roles:
  - nginx

- hosts: repeater
  remote_user: bwilson
  become: yes
  become_user: root
  roles:
  - base
  - svxlink
  - nginx
  - firewall
#  - munin
  - notification
  - backups
  - festival

# This is used to build a local debian cache server
#- hosts: support
#  remote_user: bwilson
#  become: yes
#  become_user: root
#  roles:
#  - debconf_server

- hosts: wifi_ap
# Virtual servers can't be access points
  remote_user: bwilson
  become: yes
  become_user: root
  roles:
  # This installs drivers and configures wireless
  - hardware
  # This sets up the wired and wireless interfaces
  - network

- hosts: dev
  remote_user: bwilson
  become: yes
  become_user: root
  roles:
  - development

