---
- name: Install MySQL Server and friends
  register: mysql_installed
  action: apt pkg={{ item }} force=yes
  with_items:
    - mysql-server
    - mysql-client
    - unixodbc
    - libmyodbc
    - phpmyadmin

- name: Ansible needs python-mysqldb to run the commands in configure.yml
  apt: name=python-mysqldb

- name: Make sure mysql is running
  service: name=mysql state=started

- name: Update root password for mysql; on first pass no password is needed.
  shell: >
    mysql -u root -NBe
    'SET PASSWORD FOR "root"@"localhost" = PASSWORD("{{ mysql_root_password }}");'
  when: mysql_installed.changed

- name: Build credentials file; on subsequent passes this provides authentication
  template: src=my.cnf.root.j2 dest=/root/.my.cnf mode=0600

