---
- name: Configure postfix to use a relay host
  action: template src={{ item }}.j2 dest=/etc/postfix/{{ item }} mode=0644
  with_items:
    - main.cf
    - master.cf

- name: Install sasl files
  template: src=sasl_passwd.j2 dest=/etc/postfix/sasl_passwd mode=0600

- name: Configure postfix to use TLS cacert.pem        FIXME GENERATE???
  copy: src=cacert.pem dest=/etc/postfix/ mode=0600

- name: Install some useful aliases
  template: src=aliases.j2 dest=/etc/aliases mode=0644

- name: Update the aliases map
  command: newaliases
  args:
    chdir: /etc

- name: Update the sasl password map
  command: postmap sasl_passwd
  args:
    chdir: /etc/postfix
    creates: sasl_passwd.db

- name: Start postgrey
  service: name=postgrey state=restarted

- name: Start freshclam
  service: name=clamav-freshclam state=restarted

- name: Start clamav
  service: name=clamav-daemon state=restarted

- name: Reload postfix
  service: name=postfix state=reloaded

