---
- name: Install Roundcube mail client
  apt: name=roundcube

- name: Force the password on the roundcube mysql account FIXME
  mysql_user: name=roundcube password=phoneme priv="roundcube.*:select,insert,delete,update"

- name: Creating "roundcube" database
  mysql_db: name=roundcube state=present
  register: roundcube_db_create
  
- name: Populating roundcube database
  mysql_db: name=roundcube
    state=import target=/usr/share/roundcube/SQL/mysql.initial.sql
  when: roundcube_db_create.changed

- name: Configure roundcube to use mysql
  copy: src=roundcube.config.inc.php dest=/etc/roundcube/config.inc.php mode=0640 group=www-data

- name: Install the red V
  copy: src=logo.png dest=/var/lib/roundcube/skins/classic/images/logo.png mode=0644

- name: Create the link that makes roundcube work
  file: src=/var/www/roundcube dest=/var/www/html/roundcube state=link

