---
# This is for Grandstream support at Ledson you dont want it.
#
#  This role won't work without asterisk because
#  it checks for active channels
#  but it just means the service will fail when it runs.
#  So asterisk is not listed as a dependency.
#
#  It does have 'notification' as a dependency because it shares the same virtualenv

- name: Folders for custom asterisk scripts
  file: state=directory mode=0755 name=/usr/local/asterisk

# FIXME I should probably have a version number with "version=release" 
# in here so that I don't break things by installing from the trunk instead
# of a release branch, for now I have update=no instead
- name: Install pyst2 from our github repository
  git: repo="https://github.com/brian32768/pyst2.git" dest="/usr/local/asterisk/pyst2" update=no

- name: Install pyst2 package into virtual environment
  command: chdir=/var/lib/vastra/pyst2/ /var/lib/vastra/systemd/venv/bin/python setup.py install

- name: Install systemd script
  action: copy src={{ item }} dest=/var/lib/vastra/systemd/ mode=0755
  with_items:
    - fxo.py
    - gxw.py
    - list_channels.py
    - verbose_http.py

- name: Copy requirements file for virtualenv
  copy: src=requirements_fxo.txt dest=/var/lib/vastra/systemd/

- name: Install python packages into systemd virtualenv.
  pip: virtualenv=/var/lib/vastra/systemd/venv virtualenv_python=python3 requirements=/var/lib/vastra/systemd/requirements_fxo.txt

- name: Install shell command
  copy: src=fxo dest=/usr/local/bin/ mode=0755

- name: Install service file
  copy: src=fxo.service dest=/lib/systemd/system/ mode=0644

- name: Install timer file
  copy: src=fxo.timer dest=/lib/systemd/system/ mode=0644

- name: Do the daemon-reload
  command: systemctl daemon-reload

- name: Enable systemd timer
  service: name=fxo.timer state=started enabled=yes

