---
#- name: Install files that are SITE SPECIFIC
#  action: template src={{ item }}.j2 dest=/etc/asterisk/{{ item }} mode=0644 owner=root group=vastra-backup
#  with_items:
#    - "{{ vastra_community_file }}"
#    - "{{ vastra_iax_file }}"

- name: Install TEMPLATED config files that are world-readable
  action: template src={{ item }}.j2 dest=/etc/asterisk/{{ item }} mode=0644 owner=root group=vastra-backup
  with_items:
    - extensions.conf
    - "{{ autoattendant_file }}"
    - queues.conf
    - pjsip-SIPP.conf
    - voicemail.conf

# The mysql password is embedded in res_odbc.conf and in the database,
# if you change the password in one place and don't change it in the
# other then asterisk fails That's why I keep both of them here
# together. Running this role will then sync them.

- name: Add 'asterisk' user
  mysql_user:
    login_user=root login_password={{ mysql_root_password }}
    name=asterisk password={{ mysql_asterisk_password }} 
    priv="asterisk.*:all"

- name: Install TEMPLATED config files that are secured
  action: template src={{ item }}.j2 dest=/etc/asterisk/{{ item }} mode=0640 owner=root group=vastra-backup
  with_items:
    - acl.conf
    - ari.conf
    - calendar.conf
    - pjsip.conf
    - res_odbc.conf
    - manager.conf
    - xmpp.conf

#- name: Digium G100 gateway
#  action: template src={{ item }}.j2 dest=/etc/asterisk/{{ item }} mode=0640 owner=root group=vastra-backup
#  with_items:
#    - sip_g100.conf
#    - extensions_g100.conf
#  when: have_digium_g100 == 1
#    
#- name: Sangoma gateway
#  action: template src={{ item }}.j2 dest=/etc/asterisk/{{ item }} mode=0640 owner=root group=vastra-backup
#  with_items:
#    - sip_sangoma.conf
#    - extensions_sangoma.conf
#  when: have_sangoma_gateway == 1
#
#- name: Grandstream gateway
#  action: template src={{ item }}.j2 dest=/etc/asterisk/{{ item }} mode=0640 owner=root group=vastra-backup
#  with_items:
#    - extensions_gs_gateway.conf
#    - sip_gs_gateway.conf
#  when: have_gs_gateway == 1

- name: Twilio SIP trunk
  action: template src={{ item }}.j2 dest=/etc/asterisk/{{ item }} mode=0640 owner=root group=vastra-backup
  with_items:
    - extensions_twilio.conf
  when: have_twilio_trunk == 1

#- name: Comcast SIP trunk
#  action: template src={{ item }}.j2 dest=/etc/asterisk/{{ item }} mode=0640 owner=root group=vastra-backup
#  with_items:
#    - sip_comcast.conf
#    - extensions_comcast_trunk.conf
#  when: have_comcast_trunk == 1

- name: Copy world-readable asterisk configuration
  action: copy src=Conf/{{ item }} dest=/etc/asterisk/ mode=0644 owner=root group=vastra-backup
  with_items:
    - agents.conf
    - asterisk.conf
    - ccss.conf
    - cdr.conf
    - cdr_adaptive_odbc.conf
    - cdr_manager.conf
    - cdr_odbc.conf
    - cel.conf
    - cli_aliases.conf
    - confbridge.conf
    - extconfig.conf
    - features.conf
    - followme.conf
    - func_odbc.conf
    - indications.conf
    - logger.conf
    - message_recorder.conf
    - modules.conf
    - musiconhold.conf
    - queuerules.conf
    - res_parking.conf
    - rtp.conf
    - speed_dial.conf
    - stasis.conf
    - statsd.conf
    - udptl.conf
    - valet_parking.conf

- name: Copy site specific phone hints to phone_hints.conf
  copy: src=Conf/{{ phone_hints }}.conf dest=/etc/asterisk/phone_hints.conf mode=0644 owner=root group=vastra-backup

#- name: Make folder to hold "music on hold" files.
#  file: state=directory mode=0755 name=/var/lib/custom_moh
#- name: Install custom "music on hold" files, see also the musiconhold.conf file.
#  action: copy src={{ item }} dest=/var/lib/custom_moh/
#  with_items:
#    - song1.sln
#    - song2.sln
#    - etc etc etc

- name: Install Asterisk systemd service file
  copy: src=asterisk.service dest=/lib/systemd/system/ mode=0644

- name: Install logrotate
  copy: src=logrotate dest=/etc/logrotate.d/asterisk mode=0644 owner=root group=root

# Update is set to no to avoid downloading everytime this role is played
- name: Install CDR viewer -- FIXME we need something better than this
  git: repo=https://github.com/g613/asterisk-cdr-viewer.git dest=/var/www/asterisk-cdr-viewer/ update=no

# These symbolic links work, my attempts at using nginx conf files failed. FIXME
- name: Create the link that makes cdr viewer work
  file: src=/var/www/asterisk-cdr-viewer dest=/var/www/html/cdr state=link

- name: Install Asterisk CDR viewer config files FIXME SHOULD REQUIRE AUTH LOGIN
  copy: src=asterisk-cdr-viewer.conf dest=/etc/httpd/conf-enabled/
- copy: src=acdr_config.inc.php dest=/var/www/asterisk-cdr-viewer/include/

- name: Start Asterisk service
  service: name=asterisk enabled=yes state=started
  register: asterisk_started

- name: Reload Asterisk service
  command: systemctl reload asterisk
