---
- name: Create wiki database if it does not already exist.
  mysql_db: name=wiki state=present
  register: wiki_db_create

- name: Populate database if it is new
  mysql_db: name=wiki
    state=import target=/usr/share/mediawiki/maintenance/tables.sql
  when: wiki_db_create.changed

- name: Install mediawiki LocalSettings.php from template.
  template: src=LocalSettings.php.j2 dest=/etc/mediawiki/LocalSettings.php

- name: Create the link that makes mediawiki work
  file: src=/usr/share/mediawiki dest=/var/www/html/wiki state=link
